basePath: /
definitions:
  models.Material_get:
    properties:
      category:
        type: string
      material_id:
        type: integer
      poster:
        type: string
      title:
        type: string
    type: object
  models.Userjson:
    properties:
      birthday:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      password2:
        type: string
      phone_number:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for Ozinshe app
  title: Ozinshe
  version: "1.0"
paths:
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Create account
      parameters:
      - description: User information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.Userjson'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: SignUp
      tags:
      - auth
  /foryou:
    get:
      consumes:
      - application/json
      description: random in main
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Material_get'
            type: array
      summary: GetRandom
swagger: "2.0"
